services:

# DESCOMENTA DUCKDNS SI USAS IP PUBLICA PARA CONECTARTE
#  duckdns:
#    image: lscr.io/linuxserver/duckdns:latest
#    container_name: "Duckdns_Nextcloud"
#    network_mode: host
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Madrid
#      - SUBDOMAINS=tusubdominio
#      - TOKEN=${DUCKDNS_TOKEN}
#      - UPDATE_IP=ipv4
#      - LOG_FILE=false
#    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: "Redis_Nextcloud"
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - next_backend

  db:
    image: postgres:17-alpine
    container_name: "BSD_Nextcloud"
    restart: unless-stopped
    shm_size: 256mb
    volumes:
      - PostgresNextcloudData:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    networks:
      - next_backend

  nextcloud:
    image: nextcloud:33.0.0-fpm-alpine
    container_name: "Nextcloud"
    restart: unless-stopped
    volumes:
      - NextcloudData:/var/www/html
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - TRUSTED_PROXIES=caddy
      - OVERWRITEPROTOCOL=https
    depends_on:
      - db
      - redis
    networks:
      - next_frontend
      - next_backend

  cron:
    image: nextcloud:33.0.0-fpm-alpine
    container_name: "Cron_Nextcloud"
    restart: unless-stopped
    volumes:
      - NextcloudData:/var/www/html
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - TRUSTED_PROXIES=caddy
      - OVERWRITEPROTOCOL=https
    depends_on:
      - db
      - redis
    entrypoint: /cron.sh
    networks:
      - next_frontend
      - next_backend

  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "Web_Nextcloud"
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - NextcloudData:/var/www/html:ro
      # USA ESTA CONFIGURACIÓN SI TE CONECTAS CON IP PRIVADA
      - ./caddyconfig/privado:/etc/caddy/Caddyfile:ro
      # USA ESTA CONFIGURACIÓN SI TE CONECTAS CON IP PÚBLICA
#      - ./caddyconfig/publico:/etc/caddy/Caddyfile:ro
    # QUITA ESTO SI TE CONECTAS POR IP PÚBLICA
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextcloud
    networks:
      - next_frontend

volumes:
  PostgresNextcloudData:
  NextcloudData:
  caddy_data:
  caddy_config:

networks:
  next_frontend:
    name: nextcloud_frontend
  next_backend:
    name: nextcloud_backend
    internal: true
